// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtP-nl4aLDKxFqn98pkK7AUw7f1FfOoaw',
    appId: '1:378173638930:web:ccc0a35744dca7cf384bcb',
    messagingSenderId: '378173638930',
    projectId: 'nieproject-6f36b',
    authDomain: 'nieproject-6f36b.firebaseapp.com',
    storageBucket: 'nieproject-6f36b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx1Nxuebkdi52JvduVBGfTGdv0Ln1XCSE',
    appId: '1:378173638930:android:da34320cd1029c06384bcb',
    messagingSenderId: '378173638930',
    projectId: 'nieproject-6f36b',
    storageBucket: 'nieproject-6f36b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcr3sh1NB1qpOmTZ0-BLeHoXUmOOG_S2I',
    appId: '1:378173638930:ios:31bd5a7bf18a6319384bcb',
    messagingSenderId: '378173638930',
    projectId: 'nieproject-6f36b',
    storageBucket: 'nieproject-6f36b.appspot.com',
    iosBundleId: 'com.example.nieproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcr3sh1NB1qpOmTZ0-BLeHoXUmOOG_S2I',
    appId: '1:378173638930:ios:f18f7ef80a443266384bcb',
    messagingSenderId: '378173638930',
    projectId: 'nieproject-6f36b',
    storageBucket: 'nieproject-6f36b.appspot.com',
    iosBundleId: 'com.example.nieproject.RunnerTests',
  );
}
